name:                connected-comp
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jproyo/upc-miri-tfm/connected-comp#readme
license:             BSD3
author:              Juan Pablo Royo Sales
maintainer:          juanpablo.royo@gmail.com
copyright:           Copyright (C) 2021 Juan Pablo Royo Sales
category:            Data,Data Flow,Pipes

extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -fno-warn-partial-type-signatures
  - -fconstraint-solver-iterations=0
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-top-binds
  - -fno-warn-deprecations
  - -fno-warn-orphans

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies

dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring
  - containers
  - exceptions
  - relude >= 1.0.0.0
  - unagi-chan
  - trifecta
  - time

library:
  source-dirs: src
  exposed-modules:
    - ConnComp
  when:
    - condition: false
      other-modules: Paths_connected_comp

executables:
  conn-comp:
    source-dirs:      app/DP
    main:             Main.hs
    dependencies:
      - connected-comp
    ghc-options:
      - -threaded
      - -O3
      - -rtsopts
      - -with-rtsopts=-N

  compare-graph:
    source-dirs:      app/Compare
    main:             Main.hs
    dependencies:
      - connected-comp
    ghc-options:
      - -threaded
      - -O3
      - -rtsopts
      - -with-rtsopts=-N

  benchmark:
    source-dirs:      app/Benchmark
    main:             Main.hs
    dependencies:
      - connected-comp
      - criterion
      - directory
      - time
    ghc-options:
      - -threaded
      - -O3
      - -rtsopts
      - -with-rtsopts=-N

tests:
  conn-comp-tests:
    main: Spec.hs
    source-dirs:
      - test
    build-tools:
      - hspec-discover
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      # TODO remove no warnings
      - -Wno-unused-local-binds
      - -Wno-unused-matches
    dependencies:
      - connected-comp
      - hspec == 2.*
      - QuickCheck
      - relude >= 1.0.0.0
      
